# ----------------------------------------
# ------------ Site configs --------------
# ----------------------------------------

# Replace this with domain name
site_name: SITE_NAME

# Replace this with filename of database dump located in "db/" folderD
site_dump: DUMP_FILE

# ----------------------------------------
# ----------- System configs -------------
# ----------------------------------------