- src: https://github.com/geerlingguy/ansible-role-firewall
  name: geerlingguy.firewall
  version: 1.0.9
- src: https://github.com/geerlingguy/ansible-role-apache
  name: geerlingguy.apache
  version: 1.7.2
- src: https://github.com/geerlingguy/ansible-role-git
  name: geerlingguy.git
  version: 1.1.1
- src: https://github.com/geerlingguy/ansible-role-mysql
  name: geerlingguy.mysql
  version: 2.2.3
- src: https://github.com/geerlingguy/ansible-role-php
  name: geerlingguy.php
  version: 2.0.3
- src: https://github.com/geerlingguy/ansible-role-php-pecl
  name: geerlingguy.php-pecl
  version: 1.2.1
- src: https://github.com/geerlingguy/ansible-role-php-mysql
  name: geerlingguy.php-mysql
  version: 1.2.0
- src: https://github.com/geerlingguy/ansible-role-php-xdebug
  name: geerlingguy.php-xdebug
  version: 2.1.0
- src: https://github.com/geerlingguy/ansible-role-drush
  name: geerlingguy.drush
  version: 1.1.2
- src: https://github.com/geerlingguy/ansible-role-java
  name: geerlingguy.java
  version: 1.3.0
- src: https://github.com/geerlingguy/ansible-role-solr
  name: geerlingguy.solr
  version: 3.0.0
- src: https://github.com/geerlingguy/ansible-role-composer
  name: geerlingguy.composer
  version: 1.4.1
